#!/bin/sh

echo "Symlinking /lib/ld-linux-x86-64.so.2..."
ln -s $(hab pkg path core/glibc)/lib/ld-2.22.so /lib/ld-linux-x86-64.so.2

echo "Preparing Storage..."
mkdir /hab/svc/elasticsearch/logs
mkdir /hab/svc/elasticsearch/data
mkdir /hab/svc/elasticsearch/config/scripts
chown -R hab:hab /hab/svc/elasticsearch/*


