#!/bin/sh

PKG_PATH=$(hab pkg path chefops/elasticsearch)
CFG_PATH=/hab/svc/elasticsearch/config


su hab -c "${PKG_PATH}/es/bin/elasticsearch --default.path.conf=${CFG_PATH}" 2>&1


echo "DEBUG: Leaving the run hook."
